"""Layout-Konstanten und gespeicherte Breiten."""

DASHBOARD_MAIN_MIN_WIDTH = 420
DASHBOARD_MAIN_MAX_WIDTH = 1100
DASHBOARD_MAIN_DEFAULT_WIDTH = 720

AUFTRAG_PANEL_MIN_WIDTH = 420
AUFTRAG_PANEL_MAX_WIDTH = 1100
AUFTRAG_PANEL_DEFAULT_WIDTH = 720

KEY_DASHBOARD_MAIN_WIDTH = "dashboard_main_width"
KEY_AUFTRAG_PANEL_WIDTH = "auftrag_panel_width"
